language: c
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update
install: sudo apt-get install julia
script:
    - cd src
    - julia ../test/core.jl

